### ISSUE TITLE
CMD immediately closes after double clicking the exe

### ISSUE THREAD

**Issue by Reziem** [Aetopia/NVIDIA-Driver-Downloader#4]
Hello, I've just stumbled upon your project and currently I am having an issue. I've installed it via the "scoop install https://raw.githubusercontent.com/couleur-tweak-tips/utils/main/bucket/nvddl.json" command and I also have installed the requirements (External PIP Packages used by NVIDIA Driver Downloader) via the pip install wmi. 

It seems like it works for a split second. I see the text inside the cmd window but it immediately closes milliseconds after running it. Maybe I am missing something and would love to know how to get this working :) I really love the tool and want to use it to archive all the drivers as I need them. 

Let me know if you need anymore information. I want to help in anyway I can :)

**Comment by Aetopia** [comment]
Its a CLI Tool.
https://github.com/Aetopia/NVIDIA-Driver-Downloader/wiki/CLI-Usage
You need to pass arguments to it.

**Comment by Aetopia** [comment]
I can't guarantee, it will be able to download every single NVIDIA driver version. 
(ATM, it will able to download Win 10/Win 11 Drivers. (Since these links for these platforms are hardcoded into the program.) 

NVDDL will list the most recent ones for your GPU. (Fetched via NVIDIA's API)

Also GPUs supported by NVDDL are fetched via this API Link: 
https://www.nvidia.com/Download/API/lookupValueSearch.aspx?TypeID=3

Also PIP Packages are only required if you are using the raw source code, for the compiled executables there is no need for it.

**Comment by Reziem** [comment]
> Its a CLI Tool. https://github.com/Aetopia/NVIDIA-Driver-Downloader/wiki/CLI-Usage You need to pass arguments to it.

Wow I am dumb. Sorry about that. that solved my issue 

> I can't guarantee, it will be able to download every single NVIDIA driver version. [ATM, it will able to download Win 10/Win 11 Drivers. (Since these links for these platforms are hardcoded into the program.)]
> 
> NVDDL will list the most recent driver versions ones for your GPU. (Fetched via NVIDIA's API)
> 
> Also GPUs supported by NVDDL are fetched via this API Link: https://www.nvidia.com/Download/API/lookupValueSearch.aspx?TypeID=3
> 
> Also PIP Packages are only required if you are using the raw source code, for the compiled executables there is no need for it.

No worries! Thanks for the info :)
